#!/bin/bash

cd /cromwell-executions/XRBS/a58d6736-5d98-4dae-a993-f5cfb84c14b4/call-fastqc/execution
tmpDir=$(mkdir -p "/cromwell-executions/XRBS/a58d6736-5d98-4dae-a993-f5cfb84c14b4/call-fastqc/tmp.b6beeb8d" && echo "/cromwell-executions/XRBS/a58d6736-5d98-4dae-a993-f5cfb84c14b4/call-fastqc/tmp.b6beeb8d")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/XRBS/a58d6736-5d98-4dae-a993-f5cfb84c14b4/call-fastqc/execution

)
outa58d6736="${tmpDir}/out.$$" erra58d6736="${tmpDir}/err.$$"
mkfifo "$outa58d6736" "$erra58d6736"
trap 'rm "$outa58d6736" "$erra58d6736"' EXIT
touch '/cromwell-executions/XRBS/a58d6736-5d98-4dae-a993-f5cfb84c14b4/call-fastqc/execution/stdout' '/cromwell-executions/XRBS/a58d6736-5d98-4dae-a993-f5cfb84c14b4/call-fastqc/execution/stderr'
tee '/cromwell-executions/XRBS/a58d6736-5d98-4dae-a993-f5cfb84c14b4/call-fastqc/execution/stdout' < "$outa58d6736" &
tee '/cromwell-executions/XRBS/a58d6736-5d98-4dae-a993-f5cfb84c14b4/call-fastqc/execution/stderr' < "$erra58d6736" >&2 &
(
cd /cromwell-executions/XRBS/a58d6736-5d98-4dae-a993-f5cfb84c14b4/call-fastqc/execution


fastqc -o small-xrbs_fastqc_out fastq1 fastq2
zip small-xrbs_fastqc_out
)  > "$outa58d6736" 2> "$erra58d6736"
echo $? > /cromwell-executions/XRBS/a58d6736-5d98-4dae-a993-f5cfb84c14b4/call-fastqc/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/XRBS/a58d6736-5d98-4dae-a993-f5cfb84c14b4/call-fastqc/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/XRBS/a58d6736-5d98-4dae-a993-f5cfb84c14b4/call-fastqc/execution
sync


)
mv /cromwell-executions/XRBS/a58d6736-5d98-4dae-a993-f5cfb84c14b4/call-fastqc/execution/rc.tmp /cromwell-executions/XRBS/a58d6736-5d98-4dae-a993-f5cfb84c14b4/call-fastqc/execution/rc
